### ISSUE TITLE
“Blocked loading mixed active content” issue in Firefox?

### ISSUE THREAD

**Issue by armudgal** [mitmproxy/share.mitmproxy.org#7]
## STEPS TO REPRODUCE

1. Intercept traffic using mitmproxy and save it in a file 'new'
2. Upload the file on share.mitmproxy.org

Browser: Firefox Quantum 58.0

The upload will fail and will be displayed as `Upload Failed ` in a `danger-class`
https://github.com/mitmproxy/share.mitmproxy.org/blob/f385b5c2efd4fcd3859870b1357cfdecf3a45290/upload/upload-form/upload.js#L17-L20

I think the error is being caused by `share.mitmproxy.org` being on HTTPS whereas `http://upload.share.mitmproxy.org.s3.amazonaws.com/` being on HTTP .

**Comment by mhils** [comment]
Fixed, thanks.
